# Colorscheme (gruvbox)
[colors.primary]
background = "#000000"
foreground = "#fbf1c7"

[colors.normal]
black   = '#282828'
red     = '#cc241d'
green   = '#98971a'
yellow  = '#d79921'
blue    = '#458588'
magenta = '#b16286'
cyan    = '#689d6a'
white   = '#a89984'

[colors.bright]
black   = '#928374'
red     = '#fb4934'
green   = '#b8bb26'
yellow  = '#fabd2f'
blue    = '#83a598'
magenta = '#d3869b'
cyan    = '#8ec07c'
white   = '#ebdbb2'

[window]
dimensions={columns=125, lines=40}
padding={x=15, y=15}

[scrolling]
history=2000

[font]
size=13

[font.normal]
family="FantasqueSansM Nerd Font Propo"

[cursor]
style={shape="Beam", blinking="Always"}

[keyboard]
bindings = [{key="T", mods="Control|Shift", action = "CreateNewWindow"}]
